# Generated by Django 4.0.6 on 2023-02-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('efficiency', models.IntegerField()),
                ('icon', models.ImageField(blank=True, upload_to='icons')),
                ('is_key_skill', models.BooleanField(default=False)),
            ],
        ),
    ]
