# Generated by Django 4.0.6 on 2023-03-01 12:33

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
