# Generated by Django 4.0.6 on 2023-03-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_experience_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='title',
        ),
    ]
