# Generated by Django 4.0.6 on 2023-03-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_experience_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
