# Generated by Django 4.0.6 on 2023-03-01 14:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
