# Generated by Django 4.0.6 on 2023-03-01 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_codingprofiles_icon_alter_skill_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='efficiency',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
