# Generated by Django 4.0.6 on 2023-03-04 04:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_skill_efficiency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('link', models.URLField(blank=True)),
                ('image', models.FileField(blank=True, upload_to='projects')),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
