# Generated by Django 4.0.6 on 2023-03-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_userprofile_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificateimages',
            name='certificate',
        ),
        migrations.AlterField(
            model_name='certificateimages',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
